import = [
    "~/.config/alacritty/themes/themes/personalizado.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 20
# opacity = 0.95
# blur = true

decorations = "Buttonless"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
# normal.family = "Geist Mono"
normal.family = "JetBrainsMono Nerd Font"
# normal.family = "CodeNewRoman Nerd Font Mono"
# normal.family = "ComicShannsMono Nerd Font"
# normal.family = "SpaceMono Nerd Font"
# normal.family = "MonoLisa Nerd Font Mono"
# normal.family = "CaskaydiaCove Nerd Font Mono"
# normal.family = "MesloLGS NF"
# normal.family = "Iosevka Nerd Font Mono"
# normal.family = "DankMono Nerd Font"
# line_height = 1.5


#regular
size = 14

#for video
# size = 20.0

# Lines
offset.y = 5
